main: ru.vladimirlapskiy.sudo.Main
name: sudoPlugin
version: 1.0
api-version: 1.16
commands:
   sudo:
      description: Send in chat or execute command from another player in online.
      usage: /sudo <nickname> <message or command>
      permission: sudo.sudo